[package]
name = "uwuhi"
version = "0.2.0"
edition = "2021"
description = "mDNS Service Discovery implementation"
license = "0BSD"
repository = "https://github.com/SludgePhD/uwuhi"

[dependencies]
bitflags = "1.3.2"
zerocopy = "0.6.1"
socket2 = "0.4.4"
log = "0.4.16"
smallvec = { version = "1.9.0", features = ["const_new"] }

[dev-dependencies]
env_logger = "0.9.0"
if-addrs = "0.7.0"
