[package]
name = "uwuhi-async"
version.workspace = true
edition = "2021"
description = "Async mDNS Service Discovery implementation"
license = "0BSD"
repository = "https://github.com/SludgePhD/uwuhi"

[dependencies]
uwuhi.workspace = true
log = "0.4.17"
async-io = "2.3.2"
futures-lite = "2.3.0"
